apiVersion: v1
kind: Service
metadata: 
  name: Samplewar
  labels: 
    env: prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
    protocol: TCP
  selector: 
    something: everything
    
